BUG: fix index error caused by bpm_score arrs in data_map not being same length as pv arrs
stops the following error (not happening atm on development branch, but
gets hit when other wip branches are merged):

	traceback (most recent call last):
	File "/home/nolan_work/repos/phase_ad/rf_phase_anomaly_detection/process_b.py", line 95, in look_for_new_candidates
	new_candidates: List[AnomalyCandidate] = self.buffer.find_candidates(
	File "/home/nolan_work/repos/phase_ad/rf_phase_anomaly_detection/buffer.py", line 149, in find_candidates
	scores = self.data_map["bpm_score_20"].get(start, end)
	File "/home/nolan_work/repos/phase_ad/rf_phase_anomaly_detection/sliding_window.py", line 53, in get
	raise IndexError(f"Invalid start/end indices: {s}, {e}")
	IndexError: Invalid start/end indices: 600, 720

fix is that bpm_score arrays need to stay the same length as pv arrays,
so just append 0's for now to maintain correct length.